import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/app/theme-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
      <html lang='en'>
        <body>
          <ThemeProvider attribute='class' defaultTheme='system'>
            {children}
          </ThemeProvider>
        </body>
      </html>
  )
}